[package]
name = "stack-pointer"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "A library for visualizing the execution of (imperative) computer programs"
repository = "https://github.com/SillyFreak/typst-packages/tree/main/stack-pointer"
categories = ["scripting", "presentation"]
disciplines = ["computer-science"]
keywords = ["program", "execution"]
# compiler = ""
exclude = [
  # docs and gallery are not needed in the final package
  "docs/*",
  "gallery/*",
]
